### ISSUE TITLE
Update/Maintaining Plugin

### ISSUE THREAD

**Issue by oojacoboo** [propelorm/sfPropelORMPlugin#197]
I'm curious if anyone can/will/will be updating this plugin along-side Propel's updates?  If not, would it be possible to get some documentation on what would be required to update this plugin.  Or, documentation on how you might go about using Propel in Symfony 1.4 going forward.

There is an identifier quoting issue that was supposedly fixed in 1.6.9, but I haven't been able to test.

Any information on how I might go about getting this setup would be much appreciated.  Thanks!

**Comment by rozwell** [comment]
Well, I'll try to close all the issues and since Propel1 and symfony1 aren't maintained anymore, that will be it for the plugin too.
