### ISSUE TITLE
PHP8 Support missing

### ISSUE THREAD

**Issue by devmuc** [propelorm/sfPropelORMPlugin#240]
There is a problem to embed propel/sf-propel-o-r-m-plugin to friendsofsymfony1/symfony1 with PHP8.0

`# ./symfony cc
PHP Fatal error:  Cannot declare class XMLElement, because the name is already in use in /var/symfony/vendor/propel/propel1/generator/lib/model/XMLElement.php on line 20`

only with >= PHP8.0

**Comment by mentalstring** [comment]
I'm using it with 8.1 with no issues.

Try clearing the cache folder manually?

**Comment by devmuc** [comment]
within the symfony-project?

**Comment by rozwell** [comment]
@devmuc https://github.com/FriendsOfSymfony1/symfony1/commit/5f7bf9a50acfd35c361d7da71560ada7d0102006 removed Propel plugin so I assume it's not supported by that fork.

Moreover, [sfPropelORMPlugin](https://github.com/propelorm/sfPropelORMPlugin) and [Propel](https://github.com/propelorm/Propel) were not made with intent to work on **PHP8** - which didn't even exists back then - so to be honest you're pretty much on your own with running such outdated repositories on unsupported PHP versions, sorry.

I cursorily checked and [sfPropelORMPlugin](https://github.com/propelorm/sfPropelORMPlugin) seems to run with [FriendsOfSymfony1/symfony1](https://github.com/FriendsOfSymfony1/symfony1) on PHP7.4 but it fails on PHP8.0. Maybe try playing with the autoloader to get it running on PHP8?
Good luck!

**Comment by mentalstring** [comment]
I've had good results using [sfPropelORMPlugin](https://github.com/propelorm/sfPropelORMPlugin) with [FriendsOfSymfony1/symfony1](https://github.com/FriendsOfSymfony1/symfony1) on PHP8.1 by using [this fork](https://github.com/tworzenieweb/Propel/tree/feature/php8.0) of Propel — forgot to mention that earlier and it's possibly what you are missing @devmuc.

**Comment by tutecipo** [comment]
@devmuc were you able to run sfPropelORMPlugin with PHP8.1? I'm trying to do the same thing. Thanks.

**Comment by devmuc** [comment]
> I'm using it with 8.1 with no issues.
> 
> 
> 
> Try clearing the cache manually?

Yes, we cleared the cache. Did not fix the problem.

**Comment by devmuc** [comment]
> @devmuc were you able to run sfPropelORMPlugin with PHP8.1? I'm trying to do the same thing. Thanks.

No, we were only running successfully with PHP7.4. Unfortunately
