### ISSUE TITLE
Unable to execute SELECT statement when using doSelectJoinAll

### ISSUE THREAD

**Issue by lucasaba** [propelorm/sfPropelORMPlugin#63]
I'm not sure if this could be a bug or just a specification. Anyway, here's the story.
I have three classes: `user`, `message` and `user_has_message`. In my action I had this (not wrong but bad) code:

``` php
$c = new Criteria();
$c->addDescendingOrderByColumn(MessagePeer::UPDATED_AT);
$c->addJoin(UserPeer::ID, UserHasMessagePeer::USER_ID);  //This is the bad coding
$c->add(UserHasMessagePeer::DELETED, 0);
$c->add(UserHasMessagePeer::USER_ID, $this->getUser()->getId());
$c->add(UserHasMessagePeer::READED, 0);
$this->messages = UserHasMessagePeer::doSelectJoinAll($c);
```

This code gives me an `Unable to execute SELECT statement`. The resulting SQL is something like this:

``` sql
SELECT [...] FROM INNER JOIN `user_has_message` ON [...]
```

As you can see, there's no FROM table! If I remove the `$c->addJoin(UserPeer::ID, UserHasMessagePeer::MESSAGE_ID);` from my action, everything goes smoothly! 
This same code worked with propel 1.5.
I'll investigate but any suggestion (apart from that to write a better code, wich I already know....) will be welcome!

**Comment by greddyatpt** [comment]
I'm getting the same unfriendly error: Unable to execute SELECT statement ...

This happens in propel 2.  Same code works in propel 1.7. 

All I'm doing is calling findById() on the query object.

It'll help greatly if the error message includes the exact cause of the failure.  The current message is no more useful than "oops! something went wrong."

Thanks for any help.
